version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: jewels/catalogapi
    build:
      context: .\ProductCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:7810
      DatabaseServer: mssqlserver
      DatabaseName: CatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7810:80"
    container_name: jewelscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: jewels/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:7811
    ports:
      - "7800:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver


  webmvc:
    image: jewels/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CatalogUrl: http://catalog
      IdentityUrl: http://192.168.1.30:7800
      CallBackUrl: http://localhost:7811
    ports:
      - "7811:80"
    container_name: webshop
    networks:
      - frontend
    depends_on:
      - catalog
      - tokenserver

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1448:1433"
    container_name: jewelssqlserver
    networks:
      - backend
